langue =  {
    #====== FRANCAIS ======
    "fr_FR" : {
        "" : "",
        "lang" : "Français",
        "titre" : "Le Donjon de Daleah",
        "quitter" : "Quitter",
        "options" : "Paramètres",
        ">partie" : "Charger une partie",
        "+partie" : "Créer une nouvelle partie",
        "q+sauv" : "Sauvegarder et quitter",
        "q-sauv" : "Quitter sans sauvegarder",
        "langue" : "Langue",
        "-sauv" : "Aucune sauvegarde disponible!",
        "retour" : "Retour",
        "charger" : "Charger Sauvegarde",
        "import" : "Importer",
        "suppr" : "Supprimer",
        "XP" : "Expérience :",
        "temps" : "Temps de jeu :",
        "nom" : "Nom :",
        "niv" : "Niveau :",
        "creer" : "Créer",
        "annuler" : "Annuler",
        "err" : "Erreur!",
        "déjà" : "Ce nom existe déjà!",
        "vide" : "Veuillez entrez un nom!",
        "son" : "Son du jeu",
        "plein" : "Plein écran",
        "haut" : "Monter",
        "bas" : "Descendre",
        "gauche" : "Aller à gauche",
        "droite" : "Aller à droite",
        "action" : "Interagir",
        "inv" : "INVENTAIRE",
        "1_D1" : "Clé dorée",
        "1_D+" : "Clé du niveau 2",
        "1_OP1" : "Opus: Halte!", 
        #=== à traduire et copier \/ 
        "1_OP1_q" : "34<question1>",
        "1_OP1_0" : "<réponse1>",
        "1_OP1_1" : "<réponse2>",
        "1_OP1_2" : "<réponse3>",
        "1_OP1_3" : "<réponse4>", #le nombre de réponse possible peut varier
        "1_OP1_+" : (5, 200, ""), #vie gagnée, experience gagnée, objet gagnée
        "1_OP1_-" : (-2, -200, ""), #vie gagnée, experience gagnée, objet gagnée
        #=== à traduire et copier ^^ 
        "1_OP2" : "Opus: Tu n’iras pas plus loin!",
        "1_FB1" : "Au-delà de cette porte, tu risques de rencontrer plus que ton passé…",
        "1_FB2" : "Si tu ne gagnes pas contre tes ennemis, tu ne pourras pas avancer.",
        "1_FB3" : "Si tu es ici c’est que tu as réussi… Tu t’approches de la vérité",
        "2_OP1" : "Opus: Je comptes bien te couper dans ton élan",
        "2_OP2" : "Opus: Voyons voir à quel point tu es malin...",
        "2_OP3" : "Opus: Tu ne gagneras pas contre moi!",
        "2_OP4" : "Opus: Tu ne devrais pas pouvoir être ici...",
        "2_OP5" : "Opus: Je ne te laisserais jamais emporter la clé!",
        "2_FB1" : "Les coffres te seront toujours d'aide",
        "2_FB2" : "Bouh!",
        "2_shard1"   : "Tu viens du Royaume d'Ordan: la cité des mages",
        "3_FB1" : "Le donjon de Daleah est isolé du reste des royaumes",
        "3_FB2" : "N'abandonne pas",
        "3_FB3" : "Je me demande bien quel était mon prénom...",
        "3_OP1" : "Opus: Je ne serai pas faible comme les autres",
        "3_OP2" : "Opus: Impossible...tu es arrivé jusqu'ici",
        "3_OP3" : "Opus: Les rumeurs sont donc vraies...",
        "3_shard1"   : "Ton prénom est Clay, tu as 100 ans et tu possèdes le pouvoir de crémation",
    },
    #====== ANGLAIS ======
    "en_US" : {
        "" : "",
        "lang" : "English (US)",
        "titre" : "Daleah's Dungeon",
        "quitter" : "Quit",
        "options" : "Settings",
        ">partie" : "Load a game",
        "+partie" : "Create a new game",
        "q+sauv" : "Save and quit",
        "q-sauv" : "Discard changes and quit",
        "langue" : "Language",
        "-sauv" : "No save available!",
        "retour" : "Back",
        "charger" : "Load Save",
        "import" : "Import",
        "suppr" : "Delete",
        "XP" : "Experience :",
        "temps" : "Playing time :",
        "nom" : "Name :",        
        "niv" : "Level :",
        "creer" : "Create",
        "annuler" : "Cancel",
        "err" : "Error!",
        "déjà" : "This name already exists!",
        "vide" : "Please enter a name!",
        "son" : "Game sound",
        "plein" : "Fullscreen",
        "haut" : "Go up",
        "bas" : "Go down",
        "gauche" : "Go left",
        "droite" : "Go right",
        "action" : "Interact",
        "inv" : "INVENTORY",
        "1_D1" : "Golden Key",
        "1_D+" : "Level 2 Key",
        "1_OP1" : "Opus: Halt!",
        "1_OP2" : "Opus: You will not go any further!",
        "1_FB1" : "Beyond this door, you will meet more than your past…",
        "1_FB2" : "If you don't win against your enemies, you can't move forward.",
        "1_FB3" : "If you are here, it means that you succeeded… you are getting nearer from the truth",
        "2_OP1" : "Opus: I intend to cut off your momentum",
        "2_OP2" : "Opus: Let's see how clever you are",
        "2_OP3" : "Opus: You won't win against me!",
        "2_OP4" : "Opus: You shouldn't be able to be here",
        "2_OP5" : "Opus: I won't let you take the key",
        "2_FB1" : "The chests will always be of help to you",
        "2_FB2" : "Boo!",
        "2_shard1"   : "You come from the Kingdom of Ordan: the city of mages",
        "3_FB1" : "Daleah's dungeon is isolated from the other kingdoms",
        "3_FB2" : "To reach the chest you'll need to defeat the Drak Boon",
        "3_FB3" : "I wonder what my name was...",
        "3_OP1" : "Opus: I won't be weak like the others",
        "3_OP2" : "Opus: No way...You've made it this far",
        "3_OP3" : "Opus: So the rumors are true...",
        "3_shard1"   : "Your name is Clay, you are 100 years old and have the power of cremation",
    },
}
