langue =  {
    #====== FRANCAIS ======
    "fr_FR" : {
        "lang" : "Français",
        "titre" : "je suis un titre",
        "quitter" : "Quitter",
        "options" : "Paramètres",
        ">partie" : "Charger une partie",
        "+partie" : "Créer une nouvelle partie",
        "q+sauv" : "Sauvegarder et quitter",
        "q-sauv" : "Quitter sans sauvegarder",
        "langue" : "Langue",
        "-sauv" : "Aucune sauvegarde disponible!",
        "retour" : "Retour",
        "charger" : "Charger Sauvegarde",
        "import" : "Importer",
        "XP" : "Expérience",
        "niv" : "Niveau",
        "creer" : "Créer",
        "annuler" : "Annuler",
        "err" : "Erreur!",
        "déjà" : "Ce nom existe déjà!",
        "son" : "Son du jeu",
        "plein" : "Plein écran",
        "haut" : "Monter",
        "bas" : "Descendre",
        "gauche" : "Aller à gauche",
        "droite" : "Aller à droite",
        "action" : "Interagir",
        "1_monstre1" : "Opus: Halte!",
        "1_monstre2" : "Opus: Tu n’iras pas plus loin!",
        "1_fantome1" : "Au-delà de cette porte, tu risques de rencontrer plus que ton passé…",
        "1_fantome2" : "Si tu ne gagnes pas contre tes ennemis, tu ne pourras pas avancer.",
        "1_fantome3" : "Si tu es ici c’est que tu as réussi… tu t’approches de la vérité",
    },
    #====== ANGLAIS ======
    "en_US" : {
        "lang" : "English (US)",
        "titre" : "I'm a title",
        "quitter" : "Quit",
        "options" : "Settings",
        ">partie" : "Load a game",
        "+partie" : "Create a new game",
        "q+sauv" : "Save and quit",
        "q-sauv" : "Discard changes and quit",
        "langue" : "Language",
        "-sauv" : "No save available!",
        "retour" : "Back",
        "charger" : "Load Save",
        "import" : "Import",
        "XP" : "Experience",
        "niv" : "Level",
        "creer" : "Create",
        "annuler" : "Cancel",
        "err" : "Error!",
        "déjà" : "This name already exists!",
        "son" : "Game sound",
        "plein" : "Fullscreen",
        "haut" : "Go up",
        "bas" : "Go down",
        "gauche" : "Go left",
        "droite" : "Go right",
        "action" : "Interact",
        "1_monstre1" : "Opus: Stop!",
        "1_monstre2" : "Opus: You will not go any further!",
        "1_fantome1" : "Beyond this door, you will meet more than your past…",
        "1_fantome2" : "If you don't win against your enemies, you can't move forward.",
        "1_fantome3" : "If you are here, it means that you succeeded… you are getting nearer from the truth",
    },
}