langue =  {
    #====== FRANCAIS ======
    "fr_FR" : {
        "" : "",
        "lang" : "Français",
        "titre" : "Le Donjon de Daleah",
        "quitter" : "Quitter",
        "options" : "Paramètres",
        ">partie" : "Charger une partie",
        "+partie" : "Créer une nouvelle partie",
        "q+sauv" : "Sauvegarder et quitter",
        "q-sauv" : "Quitter sans sauvegarder",
        "langue" : "Langue",
        "-sauv" : "Aucune sauvegarde disponible!",
        "retour" : "Retour",
        "charger" : "Charger Sauvegarde",
        "import" : "Importer",
        "suppr" : "Supprimer",
        "XP" : "Expérience :",
        "temps" : "Temps de jeu :",
        "nom" : "Nom :",
        "niv" : "Niveau :",
        "creer" : "Créer",
        "annuler" : "Annuler",
        "err" : "Erreur!",
        "déjà" : "Ce nom existe déjà!",
        "vide" : "Veuillez entrez un nom!",
        "son" : "Son du jeu",
        "plein" : "Plein écran",
        "haut" : "Monter",
        "bas" : "Descendre",
        "gauche" : "Aller à gauche",
        "droite" : "Aller à droite",
        "action" : "Interagir",
        "inv" : "INVENTAIRE",
        "1_D1" : "Clé dorée",
        "1_D+" : "Clé du niveau 2",
        "1_OP1" : "Opus: Halte!", 
        #=== à traduire et copier \/ 
        "1_OP1_q" : "22Je ne peux pas marcher, pourtant j'ai un dos et quatre pieds. Qui suis-je?",
        "1_OP1_0" : "un cheval paralysé",
        "1_OP1_1" : "Une chaise", #le nombre de réponse possible peut varier
        "1_OP1_+" : (5, 200, "1_D+"), #vie gagnée, experience gagnée, objet gagnée
        "1_OP1_-" : (-2, -200, ""), #vie gagnée, experience gagnée, objet gagnée
        #=== à traduire et copier ^^ 
        "1_OP2" : "Opus: Tu n’iras pas plus loin!",
        "1_FB1" : "Au-delà de cette porte, tu risques de rencontrer plus que ton passé…",
        "1_FB2" : "Si tu ne gagnes pas contre tes ennemis, tu ne pourras pas avancer.",
        "1_FB3" : "Si tu es ici c’est que tu as réussi… Tu t’approches de la vérité",
        "1_shard1": "Les mages font partis des êtres les plus puissants de tout les royaumes.",
        "2_OP1" : "Opus: Je comptes bien te couper dans ton élan",
        "2_OP1_q" : "22Je porte des lunettes mais je n'y vois rien. Qui suis-je?",
        "2_OP1_0" : "Un aveugle",
        "2_OP1_1" : "Le nez",
        "2_OP1_+" : (2,300, "","shard"),
        "2_OP1_-" : (-2,-300, ""),
        "2_OP2" : "Opus: Voyons voir à quel point tu es malin...",
        "2_OP3" : "Opus: Tu ne gagneras pas contre moi!",
        "2_OP4" : "Opus: Tu ne devrais pas pouvoir être ici...",
        "2_OP4_q" : "33Toute chose, il dévore. Il ronge le fer, mort l'acier et réduit les pierres en poussière. Qu'est-ce?",
        "2_OP4_0" : "Un dieu",
        "2_OP4_1" : "Un ogre",
        "2_OP4_2" : "Le temps",
        "2_OP4_+" : (2,350, ""),
        "2_OP4_-" : (-2,-350, ""),
        "2_OP5" : "Opus: Je ne te laisserais jamais emporter la clé!",
        "2_FB1" : "Les coffres te seront toujours d'aide",
        "2_FB2" : "Bouh!",
        "2_shard1" : "Tu viens du Royaume d'Ordan: la cité des mages",
        "2_shard2" : "Il y a 50 ans, tout les mages ont été declaré mort.",
        "2_shard3" : "L'attaque sur le Royaume d'Ordan avait été exécuter sous l'ordre de Daleah.",
        "3_FB1" : "Le donjon de Daleah est isolé du reste des royaumes.",
        "3_FB2" : "N'abandonne pas",
        "3_FB3" : "Je me demande bien quel était mon prénom...",
        "3_OP1" : "Opus: Je ne serai pas aussi faible que les autres",
        "3_OP1_q" : "12On m'entend, mais on ne me voit pas. Qui suis-je?",
        "3_OP1_0" : "La voix",
        "3_OP1_1" : "Le bruit",
        "3_OP1_+" : (3,400, "","shard"),
        "3_OP1_-" : (-3,-400, ""),
        "3_OP2" : "Opus: Impossible...tu es arrivé jusqu'ici",
        "3_OP3" : "Opus: Les rumeurs sont donc vraies...",
        "3_OP3_q" : "12Qu'est ce qui réflechit sans réfléchir?",
        "3_OP3_0" : "Un miroir",
        "3_OP3_1" : "Un reflet",
        "3_OP3_+" : (3,450, ""),
        "3_OP3_-" : (-2,-400, ""),
        "3_shard1" : "Ton prénom est Clay, tu as 100 ans et tu possèdes le pouvoir de crémation.",
        "3_shard2" : "Tu as été sauvé car tu as un but important.",
        "4_OP1" : "Opus: tu devrais repartir tant que tu le peux encore! ",
        "4_OP1_q" : "23Le fabricant n'en veut pas, l'acheteur ne s'en sert pas et l'utilisateur ne le voit pas. Qu'est ce?",
        "4_OP1_0" : "Un bijou",
        "4_OP1_1" : "Un cercueil",
        "4_OP1_2" : "Un scooter",
        "4_OP1_+" : (1,500, ""),
        "4_OP1_-" : (-2,-500, ""),
        "4_OP2" : "Opus: Personne ne me traverse.",
        "4_OP3" : "Opus: Ta gloire s'arrête ici. ",
        "4_OP3_q" : "33Si vous me cherchez je suis là. Mais quand vous m'avez trouvé, je disparais. Qui suis-je?",
        "4_OP3_0" : "La joie",
        "4_OP3_1" : "L'espoir",
        "4_OP3_2" : "Une devinette",
        "4_OP3_+" : (1,550, "","shard"),
        "4_OP3_-" : (-2,-550, ""),
        "4_OP4" : "Opus: Je ne te laisserais pas atteindre le maître!",
        "4_OP4_q" : "12 Quelle est la question à laquelle on ne peut répondre sans mentir?",
        "4_OP4_0" : "Comment vas-tu?",
        "4_OP4_1" : "Tu dors?",
        "4_OP4_+" : (3,600, ""),
        "4_OP4_-" : (-2,-600, ""),
        "4_FB1" : "Ouah... Ce n'est pas n'importe qui qui pourrait arriver jusqu'ici",
        "4_FB2" : " Je crois bien que tu y es presque...",
        "4_FB3" : "Le prochain niveau sera ton dernier...",
        "4_shard1" : "Il est possible que quelques mages aient survécu...",
        "5_DL" : "Daleah: Je ne pensais pas que tu arriverais ici si vite... Bien que cela ne signifie rien, je vais te renvoyer là où tu dois être."
    },
    #====== ANGLAIS ======
    "en_US" : {
        "" : "",
        "lang" : "English (US)",
        "titre" : "Daleah's Dungeon",
        "quitter" : "Quit",
        "options" : "Settings",
        ">partie" : "Load a game",
        "+partie" : "Create a new game",
        "q+sauv" : "Save and quit",
        "q-sauv" : "Discard changes and quit",
        "langue" : "Language",
        "-sauv" : "No save available!",
        "retour" : "Back",
        "charger" : "Load Save",
        "import" : "Import",
        "suppr" : "Delete",
        "XP" : "Experience :",
        "temps" : "Playing time :",
        "nom" : "Name :",        
        "niv" : "Level :",
        "creer" : "Create",
        "annuler" : "Cancel",
        "err" : "Error!",
        "déjà" : "This name already exists!",
        "vide" : "Please enter a name!",
        "son" : "Game sound",
        "plein" : "Fullscreen",
        "haut" : "Go up",
        "bas" : "Go down",
        "gauche" : "Go left",
        "droite" : "Go right",
        "action" : "Interact",
        "inv" : "INVENTORY",
        "1_D1" : "Golden Key",
        "1_D+" : "Level 2 Key",
        "1_OP1" : "Opus: Halt!",
        "1_OP1_q" : "12I cannot walk, yet I have a back and four feet. Who am I?",
        "1_OP1_0" : "a paralysed horse",
        "1_OP1_1" : "A chair",
        "1_OP1_+" : (5,200, ""),
        "1_OP1_-" : (-2,200, ""),
        "1_OP2" : "Opus: You will not go any further!",
        "1_FB1" : "Beyond this door, you will meet more than your past…",
        "1_FB2" : "If you don't win against your enemies, you can't move forward.",
        "1_FB3" : "If you are here, it means that you succeeded… you are getting closer to the truth",
        "1_shard1" : "The mages are one of the most powerful beings of all the kingdoms.",
        "2_OP1" : "Opus: I intend to cut off your momentum",
        "2_OP2" : "Opus: Let's see how clever you are",
        "2_OP3" : "Opus: You won't win against me!",
        "2_OP4" : "Opus: You shouldn't be able to be here",
        "2_OP4_q" : "22I wear glasses but I don't see anything. Who am I?",
        "2_OP4_0" : "A blind man",
        "2_OP4_1" : "The nose",
        "2_OP4_+" : (2,300, "","shard"),
        "2_OP4_-" : (-2,-300, ""),
        "2_OP5" : "Opus: I won't let you take the key",
        "2_FB1" : "The chests will always be of help to you",
        "2_FB2" : "Boo!",
        "2_shard1" : "You come from the Kingdom of Ordan: the city of mages",
        "2_shard2" : "50 years ago, all the mages were declared dead.",
        "2_shard3" : "The attack on the Kingdom of Ordan was executed under the order of Daleah",
        "3_FB1" : "Daleah's dungeon is isolated from the other kingdoms",
        "3_FB2" : "Don't give up",
        "3_FB3" : "I wonder what my name was...",
        "3_OP1" : "Opus: I won't be weak like the others",
        "3_OP1_q" : "33Everything, he devours. He gnaws iron, bites steel and turns stones to dust. What is it?",
        "3_OP1_0" : "A god",
        "3_OP1_1" : "An ogre",
        "3_OP1_2" : "Time",
        "3_OP1_+" : (3,400, "","shard"),
        "3_OP1_-" : (-3,-400, ""),
        "3_OP2" : "Opus: No way...You've made it this far",
        "3_OP3" : "Opus: So the rumors are true...",
        "3_OP3_q" : "12I can be heard but not seen. What am I?",
        "3_OP3_0" : "The voice",
        "3_OP3_1" : "The noise",
        "3_OP3_+" : (3,450, ""),
        "3_OP3_-" : (-3,-450, ""),
        "3_shard1" : "Your name is Clay, you are 100 years old and have the power of cremation",
        "3_shard2" : "You were saved because you have a bigger purpose",
        "4_OP1" : "Opus: You should go back while you still can!",
        "4_OP1_q" : "12What thinks without thinking?",
        "4_OP1_0" : "A mirror",
        "4_OP1_1" : "A reflection",
        "4_OP1_+" : (1,500, ""),
        "4_OP1_-" : (-1,-500, ""),
        "4_OP2" : "Opus: No one goes through me.",
        "4_OP3" : "Opus: Your glory stops here.",
        "4_OP3_q" : "12If you look for me I am here. But once you've found me I disappear. What am I?",
        "4_OP3_0" : "Happiness",
        "4_OP3_1" : "Hope",
        "4_OP3_2" : "A riddle",
        "4_OP3_+" : (1,550, "","shard"),
        "4_OP3_-" : (-1,-550, ""),
        "4_OP4" : "Opus: I will not let you reach the master!",
        "4_OP4_q" : "What is the question you cannot answer without lying?",
        "4_OP4_0" : "How are you?",
        "4_OP4_1" : "Are you sleeping?",
        "4_OP4_+" : (3,600, ""),
        "4_OP4_-" : (-2,-600, ""),
        "4_FB1" : "Wow... It's not anyone who could make it until here.",
        "4_FB2" : "I believe you're almost there...",
        "4_FB3" : "The next level will be your last...",
        "4_shard1" : "It is possible that some mages survived...",
        "5_DL" : "Daleah: I didn't think that you would make it here so fast... Although this doesn't mean anything, I shall send you back where you belong.", 
    },
}
